options:
  repo:
    type: string
    default: https://github.com/zaidka/genieacs-gui.git
    description: GenieACS GUI source code repository
  branch:
    type: string
    default: master
    description: GenieACS GUI repository deployment branch.
  genieacs_host:
    type: string
    default: ""
    description: GenieACS backend host.
  nbi_port:
    type: string
    default: "7557"
    description: GenieACS backend api port.
